(defpackage cellar-door.help
  (:use :cl)
  (:export #:main))
(in-package :cellar-door.help)

(defun main ()
  (format t "Help!~%")
  (format t "~%")
  (format t "  Commands:~%")
  (format t "    -> help: This help screen~%")
  (format t "    -> map: Save a copy of the map~%")
  (format t "    -> walk <building number>: Walks to the building number~%")
  (format t "    -> quit: Quit this game~%")
  (format t "~%")
  (format t "  Upgrades:~%")
  (format t "    -> To apply HP upgrades; add the upgrade worth to the scaling, increment the level by 1 and multiply 100 by the scaling to get the HP value.~%")
  (format t "~%")
  (format t "  Queries:~%")
  (format t "    -> Listing all tables: SELECT name FROM sqlite_master WHERE type=\"table\"~%")
  (format t "    -> Show how to create a given (player) table: SELECT sql FROM sqlite_master WHERE name=\"player\"~%")
  (format t "    -> Insert into a given (upgrades) table: INSERT INTO upgrades (type, lvl, scaling) VALUES (1, 2, 1.5)~%")
  (format t "    -> Show all columns in a table: SELECT name FROM PRAGMA_TABLE_INFO('your_table')~%")
  (force-output))
